### ISSUE TITLE
update spam protection 

### ISSUE THREAD

**Issue by chemix** [mootools/mootools-forge#11]
http://mootools.net/forge/developers

![screen shot 2014-07-28 at 22 49 42](https://cloud.githubusercontent.com/assets/42802/3726981/eb20bb4e-1698-11e4-81bf-e91d75b5f0a2.png)

**Comment by SergioCrisostomo** [comment]
@chemix  yes, Forge has been spammed lately. We have been talking about this and maybe moving plugins to npm. We will take new decisions about this shortly, now we focus on getting Core 1.5.1 out these next days. 

@timwienk is there a fast way to just clean it?

**Comment by chemix** [comment]
:+1:
