### ISSUE TITLE
Twitter login problem after change twitter nickname

### ISSUE THREAD

**Issue by chemix** [mootools/mootools-forge#4]
Hi, i changed my twitter nick and now i have no way to login into my account.
When i click on "login with twitter" button, system can create new user.

**Comment by arian** [comment]
What's your new twitter username, probably I can fix for you.

**Comment by chemix** [comment]
@chemix_cz -> @iamchemix

**Comment by arian** [comment]
can you try again?

**Comment by chemix** [comment]
thanks, it works
