### ISSUE TITLE
Problems pulling/updating the repository.

### ISSUE THREAD

**Issue by Oliv** [mootools/mootools-forge#6]
Hello,

I have an issue trying to add a new plugin in mootools forge, the update is failing at the step : Problems pulling/updating the repository.

The plugin i am trying to add : https://github.com/Oliv/Websocket.git

Do you have any clues of what is failing ?

Best regards, Olivier Gasc

**Comment by arian** [comment]
I think you need a "How To" section in the README.
And you're missing the --- and ... in your yaml header in the js file.

See also http://mootools.net/forge/how-to-add

**Comment by Oliv** [comment]
Updated, and still failing... I guess i am missing something important there.

**Comment by arian** [comment]
Also, are you using this `https://github.com/Oliv/Websocket.git` url, maybe without the .git extension it would work...

**Comment by Oliv** [comment]
Nice one, it worked with https://github.com/Oliv/Websocket

Thanks a lot, regards !
