### ISSUE TITLE
"Bad GitHub response. Try again later." on updating plugin

### ISSUE THREAD

**Issue by AndiDittrich** [mootools/mootools-forge#7]
Since one week, the mootools-forge page throws the error 
**"Bad GitHub response. Try again later."**  - Step 1/Verifying GIT Tags
on updating my plugin (http://mootools.net/forge/p/enligherjs)

the [git-repo](https://github.com/AndiDittrich/EnlighterJS/) seems to be ok and i cannot find any changes within the [git-api](http://developer.github.com/changes/)
has anyone an idea what's going wrong in mootools forge ?

best regards, andi

**Comment by arian** [comment]
I get the same issue…

**Comment by rauchg** [comment]
This could be related to the GitHub API change that enforces setting an User-Agent on the request?

**Comment by rauchg** [comment]
nvm it seems we do set user agent

**Comment by arian** [comment]
problem is that `PluginAddStepForm::fetch` is using `file_get_contents`, when using `curl` it works fine.

**Comment by lorenzos** [comment]
Has the Forge already been updated with this fix? I can't update my plugins yet.

**Comment by arian** [comment]
@lorenzos yes, but curl is still acting a bit weird on the mootools server :confused:

**Comment by AndiDittrich** [comment]
is there any reason why it's changed to curl instead of file_get_contents ? both should work..maybe it's an error wihin the server config ?

**Comment by arian** [comment]
We think the problem is that GitHub API requires the user agent to be set.

But for some unknown reason this works locally, but not on the mootools server...

``` php
<?php

$url = "https://api.github.com/repos/mootools/prime/tags";

$c = curl_init($url);
curl_setopt($c, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($c, CURLOPT_USERAGENT, 'curl/7.15.5 (i686-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.3 libidn/0.6.5');
$contents = curl_exec($c);
curl_close($c);
echo $contents;
```

**Comment by AndiDittrich** [comment]
that's strange.. are any errors available within the php errorlog or your firewall logs ?
this here is a working example how to use file_get_contents with a custom user-agent..maybe you can use it as an temporary workaround if it runs on the forge server...

``` php
class GitHubFetcher{


    public static function fetchContent($command){
        // http options
        $opts = array(
                'http'=> array(
                        'header' => 'Connection: close',
                        'method'=> 'GET',
                        'protocol_version' => '1.1',
                        'user_agent' => 'MooTools-Forge/1.0'
                )
        );

        // create new stream context
        $context = stream_context_create($opts);

        // fetch data with given http options
        return file_get_contents('https://api.github.com' . $command, false, $context);
    }

}


print_r(GitHubFetcher::fetchContent('/repos/AndiDittrich/EnlighterJS'));
```

**Comment by arian** [comment]
Awesome, that seems to work! I'll try to update the code with this class and then update the forge.

**Comment by lorenzos** [comment]
@AndiDittrich Wow, HTTP headers sent with `file_get_contents`. I didn't know it was possible. Thank you!

**Comment by AndiDittrich** [comment]
yes it's possible but a little weird... in this case you have to force to use http1.1 and define "connection: close" as first header field (http=>header can also be an array of additional header fields) ..
generally curl is the better choice in case of performance..

**Comment by AndiDittrich** [comment]
@arian now, http://mootools.net/forge/add-2 returns an "Internal Server Error 500" on update. can i help you to fix this issue ?

**Comment by arian** [comment]
Yeah, I had to remove the cache (apparently it caches the autoload php classes).

**Comment by AndiDittrich** [comment]
@arian Great work ! the forge seems to be working perfekt again :)

**Comment by tbleckert** [comment]
Still can't add plugins :(

**Comment by arian** [comment]
@tbleckert what does it say exactly?

**Comment by tbleckert** [comment]
Sorry, it says "Verifying README.md and package.yml" and in the console "POST http://mootools.net/forge/add-5 500 (Internal Server Error)" and that page itself says "The forge is a still a little dusty. Working on it! Thanks for your patience"

**Comment by arian** [comment]
It seems to be another problem:

```
<Timmeh> arian: it seems there's a problem parsing https://github.com/tbleckert/Scoreboard.js/blob/master/README.md
<Timmeh> there should just be a better check in `lib/ForgeMDParser.class.php`
<Timmeh> but it seems that `simplexml_load_string` on line 47 of that file returns false
```

Can you create another issue for this?

**Comment by tbleckert** [comment]
Of course thank you!
