### ISSUE TITLE
Twitter login is broken

### ISSUE THREAD

**Issue by abidibo** [mootools/mootools-forge#9]
Can't login with my twitter account since this morning, with either firefox or chromium, 500 error returned.

**Comment by timwienk** [comment]
I'll try to backport the fixes that we already applied in the
repository. Give me a few minutes.

**Comment by timwienk** [comment]
Can you try it now, and let us know if it works?
https://github.com/mootools/mootools-forge/commit/198f39de

Thanks for reporting, kinda forgot about it. :+1:

**Comment by timwienk** [comment]
@arian just reported it fixed, closing for now. Feel free to reopen if it's still broken.

**Comment by abidibo** [comment]
Great, it's fixed now, thanks!
